#!/bin/zsh


# This variable can be set by calling `DEVMODE=true ./ctrlr`
: ${DEVMODE:=false}
[[ "$DEVMODE" = "true" ]] && echo "Running: $(basename $0)"

PRJ_ROOT="$(cd $(dirname $0); pwd)"
SCRIPT_D="$PRJ_ROOT/script"
CONF_D="$PRJ_ROOT/.config"
ENV_VARS="$CONF_D/env_variables.sh"

# Bring in all the rest of the variables needed to figure out where everything is
source "$ENV_VARS"

#utility function
function exit_sh {
    echo "Exiting: $(basename $0)" && exit 1
}

#utility function
function help {
    echo $HELP_TEXT
    echo "Exiting: $(basename $0)" && exit 1
}
[[ "$1" = "-h" || "$1" = "help" ]] && help

[[ ! -d "$TARGET_SRC_D" ]] && echo "No source for '$NAME' found at \n\t $TARGET_SRC_D" \
    && echo "Please download your copy of the source to this directory" && \
    exit_sh 


# Run the build
if [[ "$1" = "run" ]] ; 
then
    docker run -it --rm \
    -v $PRJ_ROOT:/sandbox \
    --name $DOCKER_CONT_NAME \
    $DOCKER_IMG_NAME \
    /bin/bash "${@:2}"

elif [[ "$1" = "build" ]] ;
then
    docker build -t $DOCKER_IMG_NAME -f $DOCKERFILE .

elif [[ "$1" = "clean" ]] ;
then
    docker image rm $DOCKER_IMG_NAME
fi

echo "Exiting: $(basename $0)"
exit 0

